# Generated by Django 3.0.8 on 2020-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advlist',
            name='date',
        ),
        migrations.AddField(
            model_name='advlist',
            name='author',
            field=models.CharField(default='Default', max_length=10),
            preserve_default=False,
        ),
    ]
