# Generated by Django 3.0.8 on 2020-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advist', '0002_auto_20200719_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advistments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Advlist',
        ),
    ]
